### ISSUE TITLE
About Figure 4 in the paper. Illustration of 6 types of interactions in interactive text-to-image workflow

### ISSUE THREAD

**Issue by XuRui314** [Zeqiang-Lai/Mini-DALLE3#3]
Are all of these generated by mini-DALLE3? I wonder how the 3. Selecting is done. Because in my opinion, every time mini-DALLE3 just generates a new image according to the prompted input, so it‘s kind of impossible for the 2 images to be the same. thx

**Comment by Zeqiang-Lai** [comment]
All you need to do is adding a selecting tool. See our [v3 prompt](https://github.com/Zeqiang-Lai/Mini-DALLE3/blob/main/minidalle3/prompts/prompt-v3.txt)

**Comment by XuRui314** [comment]
I see, this ability is not implemented yet. thx
